RepositorioInfo/chacoferia/carrito/urls.py
from django.urls import path
from .views import *

app_name = "carrito"

urlpatterns = [
    path('add_product/<int:product_id>/', add_product, name='add_product'),
    path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
]

RepositorioInfo/chacoferia/templates/cart/widget.html
{% load cart_tags %}
<table class="table table-bordered">
     <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carrito de compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.cart.items %}
           {% for key, value in request.session.cart.items %}
                <tr class="text-center">
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.quantity }}</td>
                    <td>
                        <a
                            href="{% url 'carrito:add_product' value.product_id %}"
                            class="btn btn-sm btn-success"
                        >
                            +
                        </a>
                        <a
                            href="{% url 'carrito:decrement_product' value.product_id %}"
                            class="ml-2 btn-sm btn btn-danger"
                        >
                            -
                        </a>
                        Total {{ value.precio|multiply:value.quantity|money_format:"$" }}
                    </td>
                </tr>
           {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        No tienes productos en el carrito
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{ cart_total_amount|money_format:"$" }}
            </td>
        </tr>
        {% if request.session.cart.items %}
            <tr>
                <td colspan="3">
                    <a href="{% url 'process_order' %}" class="btn btn-success">Crear pedido</a>
                </td>
            </tr>
            
        {% endif %}
        <tr>
            <td colspan="3">
                <a href="{% url 'order_list' %}" class="btn btn-success">Mis pedidos</a>
            </td>
        </tr>
    </tfoot>
</table>